#!/bin/bash
# generate-compose.sh — Auto-generate docker-compose.agents.yml from existing agents
#
# Scans ~/.lobs-agents/ for agent directories and generates the compose file.
# Run this after creating/removing agents, or it runs automatically from create-agent.sh.
#
# Usage:
#   ./scripts/generate-compose.sh

set -euo pipefail

AGENTS_BASE="$HOME/.lobs-agents"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.agents.yml"

if [ ! -d "$AGENTS_BASE" ] || [ -z "$(ls -A "$AGENTS_BASE" 2>/dev/null)" ]; then
  echo "No agents found in $AGENTS_BASE"
  echo "Create one first: ./scripts/create-agent.sh <name>"
  exit 1
fi

# Start building the compose file
cat > "$COMPOSE_FILE" << 'HEADER'
# docker-compose.agents.yml — Auto-generated by scripts/generate-compose.sh
#
# Each agent is a full lobs-core instance with its own config, DB, and Discord bot.
#
# Usage:
#   docker compose -f docker-compose.agents.yml up -d
#   docker compose -f docker-compose.agents.yml logs -f <agent>
#   docker compose -f docker-compose.agents.yml down
#
# Regenerate after adding/removing agents:
#   ./scripts/generate-compose.sh

x-agent-base: &agent-base
  build:
    context: .
    dockerfile: Dockerfile.agent
  restart: unless-stopped
  environment: &agent-env
    OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
    ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
    OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    GH_TOKEN: ${GH_TOKEN:-}

services:
HEADER

VOLUMES=""

for agent_dir in "$AGENTS_BASE"/*/; do
  [ -d "$agent_dir" ] || continue
  
  name=$(basename "$agent_dir")
  
  # Read port from .port file, or default
  if [ -f "$agent_dir/.port" ]; then
    port=$(cat "$agent_dir/.port")
  else
    port=9421
  fi
  
  TOKEN_VAR="$(echo "$name" | tr '[:lower:]' '[:upper:]')_DISCORD_TOKEN"

  cat >> "$COMPOSE_FILE" << EOF
  $name:
    <<: *agent-base
    container_name: lobs-agent-$name
    environment:
      <<: *agent-env
      AGENT_NAME: $name
      LOBS_ROOT: /data
      LOBS_PORT: "9421"
      DISCORD_BOT_TOKEN: \${${TOKEN_VAR}:-}
    ports:
      - "$port:9421"
    volumes:
      - \${HOME}/.lobs-agents/$name:/data
      - $name-workspace:/home/agent

EOF

  VOLUMES="$VOLUMES  $name-workspace:\n"
done

# Add volumes section
echo "volumes:" >> "$COMPOSE_FILE"
echo -e "$VOLUMES" >> "$COMPOSE_FILE"

echo "✅ Generated $COMPOSE_FILE"
echo ""
echo "Agents:"
for agent_dir in "$AGENTS_BASE"/*/; do
  [ -d "$agent_dir" ] || continue
  name=$(basename "$agent_dir")
  port=$(cat "$agent_dir/.port" 2>/dev/null || echo "9421")
  echo "  - $name (port $port)"
done
